# Generated by Django 2.2.4 on 2019-08-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_css', models.CharField(max_length=256)),
                ('gradient_name', models.CharField(max_length=256)),
                ('gradient_author', models.CharField(max_length=256)),
            ],
        ),
    ]
